In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('mushrooms.csv')

In [3]:
df.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
df.head(n=10)

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   
5     e         x           y         y       t    a               f   
6     e         b           s         w       t    a               f   
7     e         b           y         w       t    l               f   
8     p         x           y         w       t    p               f   
9     e         b           s         y       t    a               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   
5            c         b          n  ...                        s   
6            c         b          g  ...                        s   
7            c         b          n  ...                        s   
8            c         n          p  ...                        s   
9            c         b          g  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   
5                      w                      w         p          w   
6                      w                      w         p          w   
7                      w                      w         p          w   
8                      w                      w         p          w   
9                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  
5           o         p                 k          n       g  
6           o         p                 k          n       m  
7           o         p                 n          s       m  
8           o         p                 k          v       g  
9           o         p                 k          s       m  

[10 rows x 23 columns]

In [5]:
print(df.shape)

(8124, 23)


In [6]:
# Break the data into train and test
le = LabelEncoder()
# fumnction =le.fit_transform
# Applies transformation on each columns
ds=df.apply(le.fit_transform)



In [7]:
print(type(ds))

<class 'pandas.core.frame.DataFrame'>


In [8]:
ds.head()

class  cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0      1          5            2          4        1     6                1   
1      0          5            2          9        1     0                1   
2      0          0            2          8        1     3                1   
3      1          5            3          8        1     6                1   
4      0          5            2          3        0     5                1   

   gill-spacing  gill-size  gill-color  ...  stalk-surface-below-ring  \
0             0          1           4  ...                         2   
1             0          0           4  ...                         2   
2             0          0           5  ...                         2   
3             0          1           5  ...                         2   
4             1          0           4  ...                         2   

   stalk-color-above-ring  stalk-color-below-ring  veil-type  veil-color  \
0                       7                       7          0           2   
1                       7                       7          0           2   
2                       7                       7          0           2   
3                       7                       7          0           2   
4                       7                       7          0           2   

   ring-number  ring-type  spore-print-color  population  habitat  
0            1          4                  2           3        5  
1            1          4                  3           2        1  
2            1          4                  3           2        3  
3            1          4                  2           3        5  
4            1          0                  3           0        1  

[5 rows x 23 columns]

In [9]:
data=ds.values
print(data.shape)
print(type(data))
print(data[:5,:])  # it print the first 5 rows and all the columns of the data
data_y=data[:,0] # it give all the rows and the 0th column
data_x = data[:,1:] # it gives the all the rows and all the columns from 1 st onwards 1 columns se lekar baaki saari column dega 

(8124, 23)
<class 'numpy.ndarray'>
[[1 5 2 4 1 6 1 0 1 4 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 9 1 0 1 0 0 4 0 2 2 2 7 7 0 2 1 4 3 2 1]
 [0 0 2 8 1 3 1 0 0 5 0 2 2 2 7 7 0 2 1 4 3 2 3]
 [1 5 3 8 1 6 1 0 1 5 0 3 2 2 7 7 0 2 1 4 2 3 5]
 [0 5 2 3 0 5 1 1 0 4 1 3 2 2 7 7 0 2 1 0 3 0 1]]


In [10]:
x_train,x_test,y_train,y_test=train_test_split(data_x,data_y,test_size=0.2)

In [16]:
print(y_test.shape)

(1625,)


In [19]:
print(x_test.shape[0])

1625


In [20]:
print(x_test.shape[1])

22


In [15]:
print(x_test.shape)

(1625, 22)


In [13]:
print(y_train.shape)

(6499,)


In [17]:
print(y_train.shape[0])

6499


In [18]:
print(y_train.shape[1])

IndexError: tuple index out of range

In [31]:
print(x_train.shape)
print(x_test.shape,y_test.shape)

(6499, 22)
(1625, 22) (1625,)


In [32]:
np.unique(y_train)

array([0, 1])

In [33]:
# Building Our Classifier
a=np.array([0,0,0,1,1,1,0,1])
a==1
np.sum(a==1)

4

In [34]:
def prior_prob(y_train,label):
    total_examples=y_train.shape[0]
    class_examples=np.sum(y_train==label)
    return (class_examples)/float(total_examples)
     

In [35]:
y = np.array([0,5,5,1,1,1,1,0,0])
prior_prob(y,1)

0.4444444444444444

In [36]:
# compute the likely hood


In [37]:
def cond_prob(x_train,y_train,feature_col,feature_val,label):
    x_filtered = x_train[y_train==label] # ye de rha wo saari rows jinki y_train = label 
    numerator=np.sum(x_filtered[:,feature_col]==feature_val)
    denominator = np.sum(y_train==label)
    return numerator/float(denominator)
       
    

In [38]:
# Compute posterior Prob for each test example and make predictions

In [39]:
def predict(x_train,y_train,xtest):
    """Xtest is a single testing point , n features"""
    classes=np.unique(y_train) # kitni diffrent classes hai o,1,2,3 jo bhi hai
    # compute Posterior for each class
    n_features=x_train.shape[1]  ## kitne features hai kyu ki iski shape hai (1625,22) to isme 22 different feature hogi hai in sabki saari values hai 1625 hence 1625 rows hai inko access karne ke liye 0 ka use karenge and 22 ko access karne ke liye 1 ka use karenge kyu ki 22 columns hai
    post_probs=[] #List of prob for all classes and given a single testing point
    for label in classes:
        #Post_c = liklihood*prior
        likelihood = 1.0
        for f in range(n_features):
            cond=cond_prob(x_train,y_train,f,xtest[f],label)
            likelihood*=cond
        prior = prior_prob(y_train,label)
        post = likelihood*prior
        post_probs.append(post)
    pred = np.argmax(post_probs)
    return pred
    

In [40]:
output = predict(x_train,y_train,x_test[1])
print(output)
print(y_test[1])

0
0


In [41]:
 def score(x_train,y_train,x_test,y_test):
        pred=[]
        for i in range(x_test.shape[0]):
            pred_label=predict(x_train,y_train,x_test[i])
            pred.append(pred_label)
        pred = np.array(pred)
        accuracy = np.sum(pred==y_test)/y_test.shape[0]
        return accuracy

In [42]:
print(score(x_train,y_train,x_test,y_test))

0.9975384615384615
